### ISSUE TITLE
Parse.py causes error

### ISSUE THREAD

**Issue by Vadskye** [funginstitute/patentprocessor#14]
Only works when move_tables(output_directory) on line 114 is commented out.
Error message:
Traceback (most recent call last):
  File "parse.py", line 129, in <module>
    main(PATENTROOT, XMLREGEX, VERBOSITY, PATENTOUTPUTDIR)
  File "parse.py", line 115, in main
    move_tables(output_directory)
  File "parse.py", line 98, in move_tables
    shutil.copy(database,output_directory+'/'+database)
  File "c:\Python27\lib\shutil.py", line 119, in copy
    copyfile(src, dst)
  File "c:\Python27\lib\shutil.py", line 69, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))
shutil.Error: `assignee.sqlite3` and `./assignee.sqlite3` are the same file

**Comment by gtfierro** [comment]
Issues fixed as of c94a5bc27
