### ISSUE TITLE
Test files can't find grant_handler_v43

### ISSUE THREAD

**Issue by Vadskye** [funginstitute/patentprocessor#22]
The test_configuration.py and test_parse_file.py tests cannot find the handler they need to run. The error given is as follows:
Traceback (most recent call last):
  File "test_parse_file.py", line 12, in <module>
    import parse
  File "..\parse.py", line 21, in <module>
    xmlhandlers = get_xml_handlers('process.cfg')
  File "..\lib\config_parser.py", line 87, in get_xml_handlers
    xmlhandlers[year] = importlib.import_module(handler)
  File "c:\Python27\lib\importlib__init__.py", line 37, in import_module
    **import**(name)
ImportError: No module named grant_handler_v43

In /lib/handlers, there appears to only be grant_handler_v42 and grant_handler_v44, but no _v43.

**Comment by gtfierro** [comment]
This is a typo in the test/process.cfg file. Will be fixed in upcoming pull request

**Comment by gtfierro** [comment]
Fixed in #23
