### ISSUE TITLE
Problems getting it up and running

### ISSUE THREAD

**Issue by RodogInfinite** [funginstitute/patentprocessor#88]
First started with a SQLite database but couldn't get it running properly. Switched to MySQL and everything runs until this traceback occurs

> Traceback (most recent call last):
  File "consolidate.py", line 182, in <module>
    join('disambiguator.csv')
  File "consolidate.py", line 167, in join
    old[0] = old[0].astype(str)
  File "/home/user/patentprocessor/venv/local/lib/python2.7/site-packages/pandas/core/frame.py", line 2003, in __getitem__
    return self._get_item_cache(key)
  File "/home/user/patentprocessor/venv/local/lib/python2.7/site-packages/pandas/core/generic.py", line 667, in _get_item_cache
    values = self._data.get(item)
  File "/home/user/patentprocessor/venv/local/lib/python2.7/site-packages/pandas/core/internals.py", line 1655, in get
    _, block = self._find_block(item)
  File "/home/user/patentprocessor/venv/local/lib/python2.7/site-packages/pandas/core/internals.py", line 1935, in _find_block
    self._check_have(item)
  File "/home/user/patentprocessor/venv/local/lib/python2.7/site-packages/pandas/core/internals.py", line 1942, in _check_have
    raise KeyError('no item named %s' % com.pprint_thing(item))
KeyError: u'no item named 0'

It turns out that line 165 and 166 

```
old = s.execute('select uuid, inventor_id from rawinventor where inventor_id != "";')
old = pd.DataFrame.from_records(old.fetchall())
```

produce an empty dataframe because there are no recorded inventor_ids in the table.

**Comment by RodogInfinite** [comment]
Note: these are no longer accessible
[loctbl](https://s3-us-west-1.amazonaws.com/fidownloads/loctbl.sqlite3)
[NBER_asg](https://s3-us-west-1.amazonaws.com/fidownloads/NBER_asg)

**Comment by RodogInfinite** [comment]
Connected a MySQL database and instead of using SQLite.  I had to convert all non-id columns to utf8mb4 for everything to work. Got the assignee disambiguation and the lawyer disambiguation to populate the clean columns, but the geo disambiguation gives basically the same traceback.

```
geocoding started 2016-12-14 11:13:13.276278
List of all valid Google input_address values constructed with 248183 items
rm: cannot remove 'disambiguator.csv': No such file or directory
Running consolidation for disambiguator

... running year for grant...
...running year for application...

sys:1: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
Traceback (most recent call last):
  File "consolidate.py", line 175, in <module>
    join('disambiguator.csv')
  File "consolidate.py", line 162, in join
    old[0] = old[0].astype(str)
  File "/home/user/anaconda2/lib/python2.7/site-packages/pandas/core/frame.py", line 1997, in __getitem__
    return self._getitem_column(key)
  File "/home/user/anaconda2/lib/python2.7/site-packages/pandas/core/frame.py", line 2004, in _getitem_column
    return self._get_item_cache(key)
  File "/home/user/anaconda2/lib/python2.7/site-packages/pandas/core/generic.py", line 1350, in _get_item_cache
    values = self._data.get(item)
  File "/home/user/anaconda2/lib/python2.7/site-packages/pandas/core/internals.py", line 3290, in get
    loc = self.items.get_loc(item)
  File "/home/user/anaconda2/lib/python2.7/site-packages/pandas/indexes/base.py", line 1947, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:4154)
  File "pandas/index.pyx", line 159, in pandas.index.IndexEngine.get_loc (pandas/index.c:4018)
  File "pandas/hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12368)
  File "pandas/hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12322)
KeyError: 0

```

**Comment by RodogInfinite** [comment]
I dropped the table and created a fresh one. Then I changed the default character set using 

```
ALTER DATABASE foo
DEFAULT CHARACTER SET = 'utf8mb4' DEFAULT COLLATE 'utf8mb4_unicode_ci'
```
the KeyError went away, but left me with a new problem. PyCharm kills consolidate.py with 

> exit code 137 (interrupted by signal 9: SIGKILL)

Which suggests a memory bottleneck. From the shell running `./run_consolidation.sh` or `python consolidate.py` it just ends with "Killed". I used `top` in another shell to monitor memory usage and Python peaks at about 90% of my 8GB available. Before upgrading my RAM I've been seeking software solutions, but so far no luck. I've used memory profiler to produce the attached graph which doesn't immediately provide any useful insights. 
![figure_1](https://cloud.githubusercontent.com/assets/22568404/21511796/3ecd157a-cc73-11e6-8107-fbf9992867b0.png)

I after making sure it wasn't just 2015 data that was causing the problem I switched to 2014. 

Once run it pauses on 

> running year 2014 ... for grant 

for some time. A new disambiguator.csv is created. I used print statements in the `main(year, doctype)`  function to print `tmprow` and `newrow` to try to track when the program breaks. Many lines are printed successfully, but there's no way for me to know if every record is transferred to the csv as it just stops printing with no hint as to why while still consuming an average of about 80% mem usage seen from `top`. Using print statements in the `join(newfile)` function doesn't produce anything which suggests that the problem is somewhere in the `main(year, doctype)` function that breaks it before the join can be executed. I've avoided the unit tests because they couldn't find the modules and I'm still very new to Python and hadn't used unit tests yet, but I'm going to try to get them up and running because I haven't made much progress past this point. Any suggestions are welcome.

**Comment by RodogInfinite** [comment]
Started fresh and used "latest" because it limited the number of files in the datadir to one, "ipg150317". The process doesn't kill itself and proceeds to the join function, but terminates with the following traceback, another key error: 

> Name: 0, dtype: object
Traceback (most recent call last):
  File "consolidate.py", line 181, in <module>
    join('disambiguator.csv')
  File "consolidate.py", line 166, in join
    old[0] = old[0].astype(str)
  File "/home/user/anaconda2/lib/python2.7/site-packages/pandas/core/frame.py", line 1997, in __getitem__
    return self._getitem_column(key)
  File "/home/user/anaconda2/lib/python2.7/site-packages/pandas/core/frame.py", line 2004, in _getitem_column
    return self._get_item_cache(key)
  File "/home/user/anaconda2/lib/python2.7/site-packages/pandas/core/generic.py", line 1350, in _get_item_cache
    values = self._data.get(item)
  File "/home/user/anaconda2/lib/python2.7/site-packages/pandas/core/internals.py", line 3290, in get
    loc = self.items.get_loc(item)
  File "/home/user/anaconda2/lib/python2.7/site-packages/pandas/indexes/base.py", line 1947, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:4154)
  File "pandas/index.pyx", line 159, in pandas.index.IndexEngine.get_loc (pandas/index.c:4018)
  File "pandas/hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12368)
  File "pandas/hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12322)
KeyError: 0

**Comment by Bernaz** [comment]
Hi @RodogInfinite, I had the same error. Did you manage to fix the problem?
